#!/usr/bin/env python3
"""Üret: data/careers/professions.json (200) + departments.json (tüm ana bölümler)."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "careers"

TEMPLATES = {
    "tech_analytical": {
        "holland": {"R": 2, "I": 4, "A": 1, "S": 0, "E": 0, "C": 2},
        "mbtiIdeal": {"ei": -0.15, "sn": 0.4, "tf": 0.5, "jp": -0.2},
        "values": {"growth": 0.35, "autonomy": 0.3, "achievement": 0.2},
        "vark": {"V": 2, "A": 1, "R": 3, "K": 2},
        "strengths": {"analytical": 0.35, "learning": 0.25, "focus": 0.25},
        "enneagram": {"5": 0.45, "1": 0.15, "6": 0.12},
    },
    "tech_creative": {
        "holland": {"R": 1, "I": 2, "A": 4, "S": 1, "E": 1, "C": 1},
        "mbtiIdeal": {"ei": 0.1, "sn": 0.35, "tf": 0.0, "jp": 0.25},
        "values": {"creativity": 0.35, "autonomy": 0.25, "variety": 0.2},
        "vark": {"V": 4, "A": 1, "R": 1, "K": 2},
        "strengths": {"creative": 0.35, "communication": 0.2, "learning": 0.2},
        "enneagram": {"4": 0.35, "7": 0.25, "3": 0.15},
    },
    "health_clinical": {
        "holland": {"R": 2, "I": 3, "A": 0, "S": 4, "E": 0, "C": 2},
        "mbtiIdeal": {"ei": -0.1, "sn": 0.1, "tf": 0.15, "jp": -0.35},
        "values": {"service": 0.4, "security": 0.2, "purpose": 0.25},
        "vark": {"V": 2, "A": 2, "R": 3, "K": 3},
        "strengths": {"empathy": 0.35, "discipline": 0.25, "analytical": 0.2},
        "enneagram": {"2": 0.35, "6": 0.25, "1": 0.15},
    },
    "health_support": {
        "holland": {"R": 1, "I": 2, "A": 0, "S": 4, "E": 1, "C": 2},
        "mbtiIdeal": {"ei": 0.05, "sn": 0.0, "tf": -0.1, "jp": -0.2},
        "values": {"service": 0.45, "community": 0.2, "balance": 0.15},
        "vark": {"V": 2, "A": 3, "R": 2, "K": 2},
        "strengths": {"empathy": 0.4, "communication": 0.25, "relationship": 0.2},
        "enneagram": {"2": 0.4, "9": 0.2},
    },
    "engineering": {
        "holland": {"R": 4, "I": 3, "A": 1, "S": 0, "E": 1, "C": 2},
        "mbtiIdeal": {"ei": -0.2, "sn": 0.15, "tf": 0.45, "jp": -0.25},
        "values": {"achievement": 0.3, "growth": 0.25, "security": 0.15},
        "vark": {"V": 3, "A": 1, "R": 3, "K": 3},
        "strengths": {"analytical": 0.35, "execution": 0.3, "discipline": 0.2},
        "enneagram": {"1": 0.25, "5": 0.3, "6": 0.2},
    },
    "sales_enterprise": {
        "holland": {"R": 0, "I": 1, "A": 1, "S": 2, "E": 4, "C": 2},
        "mbtiIdeal": {"ei": 0.55, "sn": 0.2, "tf": 0.15, "jp": 0.2},
        "values": {"achievement": 0.35, "recognition": 0.25, "adventure": 0.15},
        "vark": {"V": 2, "A": 4, "R": 1, "K": 1},
        "strengths": {"communication": 0.35, "leadership": 0.25, "adaptability": 0.2},
        "enneagram": {"3": 0.4, "8": 0.25, "7": 0.15},
    },
    "finance_ops": {
        "holland": {"R": 0, "I": 3, "A": 0, "S": 1, "E": 2, "C": 4},
        "mbtiIdeal": {"ei": -0.05, "sn": -0.1, "tf": 0.45, "jp": -0.45},
        "values": {"security": 0.35, "achievement": 0.3, "growth": 0.15},
        "vark": {"V": 3, "A": 1, "R": 4, "K": 1},
        "strengths": {"analytical": 0.4, "discipline": 0.3, "focus": 0.15},
        "enneagram": {"1": 0.3, "6": 0.25, "5": 0.2},
    },
    "legal_public": {
        "holland": {"R": 0, "I": 3, "A": 0, "S": 2, "E": 3, "C": 3},
        "mbtiIdeal": {"ei": 0.15, "sn": 0.0, "tf": 0.35, "jp": -0.35},
        "values": {"purpose": 0.25, "security": 0.25, "achievement": 0.2},
        "vark": {"V": 1, "A": 3, "R": 4, "K": 1},
        "strengths": {"analytical": 0.3, "communication": 0.3, "strategic": 0.2},
        "enneagram": {"1": 0.35, "6": 0.25, "8": 0.15},
    },
    "education": {
        "holland": {"R": 0, "I": 3, "A": 2, "S": 4, "E": 2, "C": 2},
        "mbtiIdeal": {"ei": 0.25, "sn": 0.15, "tf": -0.15, "jp": 0.0},
        "values": {"purpose": 0.35, "service": 0.3, "community": 0.2},
        "vark": {"V": 2, "A": 4, "R": 2, "K": 2},
        "strengths": {"communication": 0.35, "empathy": 0.25, "relationship": 0.2},
        "enneagram": {"2": 0.35, "9": 0.2, "1": 0.15},
    },
    "science_research": {
        "holland": {"R": 2, "I": 5, "A": 1, "S": 0, "E": 0, "C": 2},
        "mbtiIdeal": {"ei": -0.35, "sn": 0.35, "tf": 0.35, "jp": -0.1},
        "values": {"growth": 0.35, "purpose": 0.25, "autonomy": 0.2},
        "vark": {"V": 2, "A": 1, "R": 4, "K": 2},
        "strengths": {"analytical": 0.45, "learning": 0.3, "focus": 0.15},
        "enneagram": {"5": 0.5, "4": 0.15, "1": 0.12},
    },
    "arts_media": {
        "holland": {"R": 1, "I": 1, "A": 5, "S": 1, "E": 2, "C": 0},
        "mbtiIdeal": {"ei": 0.2, "sn": 0.45, "tf": -0.05, "jp": 0.35},
        "values": {"creativity": 0.4, "recognition": 0.2, "variety": 0.25},
        "vark": {"V": 4, "A": 2, "R": 1, "K": 2},
        "strengths": {"creative": 0.45, "communication": 0.25, "adaptability": 0.15},
        "enneagram": {"4": 0.35, "7": 0.3, "3": 0.2},
    },
    "service_hospitality": {
        "holland": {"R": 1, "I": 0, "A": 1, "S": 3, "E": 3, "C": 2},
        "mbtiIdeal": {"ei": 0.35, "sn": -0.1, "tf": -0.1, "jp": 0.15},
        "values": {"community": 0.25, "variety": 0.2, "balance": 0.2},
        "vark": {"V": 2, "A": 3, "R": 1, "K": 3},
        "strengths": {"communication": 0.3, "adaptability": 0.3, "relationship": 0.25},
        "enneagram": {"2": 0.3, "7": 0.25, "9": 0.2},
    },
    "logistics_production": {
        "holland": {"R": 4, "I": 1, "A": 0, "S": 1, "E": 1, "C": 4},
        "mbtiIdeal": {"ei": -0.15, "sn": -0.2, "tf": 0.35, "jp": -0.4},
        "values": {"security": 0.25, "achievement": 0.25, "growth": 0.15},
        "vark": {"V": 2, "A": 1, "R": 2, "K": 4},
        "strengths": {"execution": 0.35, "discipline": 0.3, "analytical": 0.15},
        "enneagram": {"1": 0.3, "6": 0.25, "8": 0.15},
    },
    "agri_env": {
        "holland": {"R": 4, "I": 3, "A": 0, "S": 1, "E": 1, "C": 2},
        "mbtiIdeal": {"ei": -0.25, "sn": 0.0, "tf": 0.2, "jp": -0.15},
        "values": {"purpose": 0.3, "balance": 0.2, "community": 0.15},
        "vark": {"V": 2, "A": 1, "R": 3, "K": 4},
        "strengths": {"analytical": 0.25, "execution": 0.25, "learning": 0.2},
        "enneagram": {"9": 0.25, "5": 0.2, "1": 0.15},
    },
    "hr_people": {
        "holland": {"R": 0, "I": 2, "A": 1, "S": 4, "E": 2, "C": 2},
        "mbtiIdeal": {"ei": 0.25, "sn": 0.1, "tf": -0.2, "jp": 0.05},
        "values": {"service": 0.25, "community": 0.25, "growth": 0.2},
        "vark": {"V": 2, "A": 3, "R": 2, "K": 2},
        "strengths": {"empathy": 0.35, "communication": 0.3, "relationship": 0.25},
        "enneagram": {"2": 0.35, "9": 0.25, "6": 0.15},
    },
    "security_defense": {
        "holland": {"R": 3, "I": 2, "A": 0, "S": 2, "E": 2, "C": 3},
        "mbtiIdeal": {"ei": 0.0, "sn": -0.15, "tf": 0.4, "jp": -0.45},
        "values": {"security": 0.4, "purpose": 0.2, "achievement": 0.15},
        "vark": {"V": 2, "A": 2, "R": 2, "K": 3},
        "strengths": {"discipline": 0.35, "execution": 0.25, "strategic": 0.2},
        "enneagram": {"6": 0.35, "8": 0.25, "1": 0.2},
    },
}

# (title, category, template, future 1-10)
_PROF_RAW = [
    # Yazılım & dijital (22)
    ("Yazılım Geliştirici", "Dijital", "tech_analytical", 9),
    ("Backend Geliştirici", "Dijital", "tech_analytical", 9),
    ("Frontend Geliştirici", "Dijital", "tech_creative", 9),
    ("Full Stack Geliştirici", "Dijital", "tech_analytical", 9),
    ("Mobil Uygulama Geliştirici", "Dijital", "tech_analytical", 9),
    ("DevOps Mühendisi", "Dijital", "tech_analytical", 9),
    ("Bulut Mimarı", "Dijital", "tech_analytical", 9),
    ("Siber Güvenlik Uzmanı", "Dijital", "tech_analytical", 9),
    ("Veri Bilimci", "Dijital", "tech_analytical", 9),
    ("Makine Öğrenmesi Mühendisi", "Dijital", "tech_analytical", 9),
    ("Veri Mühendisi", "Dijital", "tech_analytical", 9),
    ("BI Analisti", "Dijital", "tech_analytical", 8),
    ("Ürün Yöneticisi (Yazılım)", "Dijital", "sales_enterprise", 9),
    ("Scrum Master", "Dijital", "hr_people", 8),
    ("QA Test Mühendisi", "Dijital", "tech_analytical", 8),
    ("Oyun Geliştirici", "Dijital", "tech_creative", 8),
    ("XR/AR Geliştirici", "Dijital", "tech_creative", 8),
    ("Blockchain Geliştirici", "Dijital", "tech_analytical", 7),
    ("ERP Uzmanı", "Dijital", "finance_ops", 8),
    ("Sistem Yöneticisi", "Dijital", "tech_analytical", 8),
    ("Ağ Mühendisi", "Dijital", "engineering", 8),
    ("Teknik Destek Uzmanı", "Dijital", "service_hospitality", 7),
    # Mühendislik (28)
    ("Bilgisayar Mühendisi", "Mühendislik", "engineering", 9),
    ("Elektrik-Elektronik Mühendisi", "Mühendislik", "engineering", 8),
    ("Endüstri Mühendisi", "Mühendislik", "engineering", 8),
    ("Makine Mühendisi", "Mühendislik", "engineering", 8),
    ("İnşaat Mühendisi", "Mühendislik", "engineering", 8),
    ("Kimya Mühendisi", "Mühendislik", "engineering", 8),
    ("Metalurji Mühendisi", "Mühendislik", "engineering", 7),
    ("Gıda Mühendisi", "Mühendislik", "engineering", 8),
    ("Tekstil Mühendisi", "Mühendislik", "engineering", 7),
    ("Çevre Mühendisi", "Mühendislik", "agri_env", 8),
    ("Jeoloji Mühendisi", "Mühendislik", "science_research", 7),
    ("Petrol ve Doğalgaz Mühendisi", "Mühendislik", "engineering", 8),
    ("Harita Mühendisi", "Mühendislik", "engineering", 7),
    ("Uçak Mühendisi", "Mühendislik", "engineering", 8),
    ("Uzay Mühendisi", "Mühendislik", "engineering", 8),
    ("Otomotiv Mühendisi", "Mühendislik", "engineering", 8),
    ("Biyomedikal Mühendisi", "Mühendislik", "health_clinical", 9),
    ("Enerji Sistemleri Mühendisi", "Mühendislik", "engineering", 8),
    ("Yapı Mühendisi", "Mühendislik", "engineering", 8),
    ("Geoteknik Mühendisi", "Mühendislik", "engineering", 7),
    ("İş Sağlığı ve Güvenliği Mühendisi", "Mühendislik", "health_support", 8),
    ("Kalite Mühendisi", "Mühendislik", "logistics_production", 8),
    ("Üretim Mühendisi", "Mühendislik", "logistics_production", 8),
    ("Proses Mühendisi", "Mühendislik", "engineering", 8),
    ("Malzeme Mühendisi", "Mühendislik", "science_research", 8),
    ("Nükleer Mühendisi", "Mühendislik", "science_research", 7),
    ("Denizcilik Mühendisi", "Mühendislik", "engineering", 7),
    ("Maden Mühendisi", "Mühendislik", "engineering", 7),
    # Sağlık (22)
    ("Pratisyen Hekim", "Sağlık", "health_clinical", 9),
    ("Uzman Doktor", "Sağlık", "health_clinical", 9),
    ("Diş Hekimi", "Sağlık", "health_clinical", 8),
    ("Eczacı", "Sağlık", "health_clinical", 8),
    ("Hemşire", "Sağlık", "health_support", 8),
    ("Fizyoterapist", "Sağlık", "health_support", 8),
    ("Beslenme ve Diyetisyen", "Sağlık", "health_support", 8),
    ("Psikolog", "Sağlık", "health_support", 9),
    ("Psikiyatrist", "Sağlık", "health_clinical", 9),
    ("Tıbbi Laborant", "Sağlık", "science_research", 7),
    ("Radyoloji Teknikeri", "Sağlık", "health_clinical", 7),
    ("Anestezi Teknikeri", "Sağlık", "health_clinical", 8),
    ("Odyolog", "Sağlık", "health_support", 7),
    ("Konuşma ve Dil Terapisti", "Sağlık", "health_support", 8),
    ("Ergoterapist", "Sağlık", "health_support", 7),
    ("Sosyal Hizmet Uzmanı", "Sağlık", "health_support", 8),
    ("Halk Sağlığı Uzmanı", "Sağlık", "health_clinical", 8),
    ("Biyomedikal Teknikeri", "Sağlık", "engineering", 8),
    ("Veteriner Hekim", "Sağlık", "health_clinical", 8),
    ("Optisyen", "Sağlık", "health_support", 7),
    ("İlk ve Acil Yardım Teknisyeni", "Sağlık", "health_support", 7),
    ("Tıbbi Sekreter", "Sağlık", "finance_ops", 6),
    # Eğitim (12)
    ("Sınıf Öğretmeni", "Eğitim", "education", 7),
    ("Okul Öncesi Öğretmeni", "Eğitim", "education", 7),
    ("İngilizce Öğretmeni", "Eğitim", "education", 7),
    ("Matematik Öğretmeni", "Eğitim", "education", 8),
    ("Özel Eğitim Öğretmeni", "Eğitim", "education", 8),
    ("Üniversite Öğretim Görevlisi", "Eğitim", "education", 8),
    ("Eğitim Koçu", "Eğitim", "hr_people", 8),
    ("Kurumsal Eğitmen", "Eğitim", "education", 8),
    ("İdareci/Müdür", "Eğitim", "sales_enterprise", 7),
    ("Rehber Öğretmen", "Eğitim", "education", 8),
    ("Kütüphaneci", "Eğitim", "finance_ops", 6),
    ("Akademik Danışman", "Eğitim", "hr_people", 7),
    # İş & finans (20)
    ("Finansal Analist", "İş", "finance_ops", 8),
    ("Muhasebeci", "İş", "finance_ops", 7),
    ("Denetçi", "İş", "finance_ops", 8),
    ("Yatırım Uzmanı", "İş", "finance_ops", 8),
    ("Risk Yöneticisi", "İş", "finance_ops", 8),
    ("İş Analisti", "İş", "tech_analytical", 9),
    ("Proje Yöneticisi", "İş", "sales_enterprise", 8),
    ("Operasyon Müdürü", "İş", "logistics_production", 8),
    ("Tedarik Zinciri Uzmanı", "İş", "logistics_production", 8),
    ("Satınalma Uzmanı", "İş", "sales_enterprise", 7),
    ("İnsan Kaynakları Uzmanı", "İş", "hr_people", 8),
    ("İşe Alım Uzmanı", "İş", "hr_people", 8),
    ("Ücret ve Yan Haklar Uzmanı", "İş", "finance_ops", 7),
    ("Strateji Danışmanı", "İş", "sales_enterprise", 9),
    ("Yönetim Danışmanı", "İş", "sales_enterprise", 9),
    ("Girişimci / Kurucu", "İş", "sales_enterprise", 8),
    ("Franchise Yöneticisi", "İş", "sales_enterprise", 7),
    ("E-ticaret Yöneticisi", "İş", "sales_enterprise", 8),
    ("Marka Yöneticisi", "İş", "arts_media", 8),
    ("Patent ve Fikri Mülkiyet Uzmanı", "İş", "legal_public", 8),
    # Hukuk & kamu (14)
    ("Avukat", "Hukuk", "legal_public", 8),
    ("Hâkim", "Hukuk", "legal_public", 8),
    ("Savcı", "Hukuk", "legal_public", 8),
    ("Noter", "Hukuk", "legal_public", 7),
    ("Kurumsal Hukuk Müşaviri", "Hukuk", "legal_public", 9),
    ("Uyum (Compliance) Uzmanı", "Hukuk", "legal_public", 8),
    ("Kamu Personeli", "Kamu", "finance_ops", 7),
    ("Diplomat", "Kamu", "legal_public", 8),
    ("Siyaset Bilimci (Kurumsal)", "Kamu", "legal_public", 7),
    ("Belediye Uzmanı", "Kamu", "legal_public", 7),
    ("SGK Uzmanı", "Kamu", "finance_ops", 7),
    ("Gümrük Müşaviri", "Kamu", "legal_public", 7),
    ("Sosyal Güvenlik Denetmeni", "Kamu", "finance_ops", 7),
    ("İç Denetçi", "Kamu", "finance_ops", 8),
    # Bilim & AR-GE (14)
    ("Araştırma Görevlisi", "Bilim", "science_research", 7),
    ("Laboratuvar Araştırmacısı", "Bilim", "science_research", 8),
    ("Kimyager", "Bilim", "science_research", 7),
    ("Biyolog", "Bilim", "science_research", 8),
    ("Fizikçi", "Bilim", "science_research", 8),
    ("Matematikçi", "Bilim", "science_research", 8),
    ("İstatistikçi", "Bilim", "science_research", 9),
    ("Meteorolog", "Bilim", "science_research", 7),
    ("Coğrafyacı", "Bilim", "science_research", 7),
    ("Arkeolog (kazı)", "Bilim", "science_research", 6),
    ("Restoratör", "Bilim", "arts_media", 7),
    ("Patoloji Uzmanı", "Bilim", "health_clinical", 8),
    ("Farmakolog", "Bilim", "science_research", 8),
    ("Genetik Danışman", "Bilim", "health_support", 8),
    # Sanat & medya (18)
    ("Grafik Tasarımcı", "Sanat", "arts_media", 8),
    ("UX Tasarımcısı", "Sanat", "tech_creative", 9),
    ("UI Tasarımcısı", "Sanat", "tech_creative", 9),
    ("Ürün Tasarımcısı", "Sanat", "arts_media", 8),
    ("İç Mimar", "Sanat", "arts_media", 8),
    ("Mimar", "Sanat", "engineering", 8),
    ("Şehir Plancı", "Sanat", "engineering", 8),
    ("Fotoğrafçı", "Sanat", "arts_media", 7),
    ("Video Prodüksiyon Uzmanı", "Sanat", "arts_media", 8),
    ("Sinematograf", "Sanat", "arts_media", 7),
    ("Editör", "Sanat", "arts_media", 7),
    ("Muhabir", "Sanat", "arts_media", 7),
    ("İçerik Üreticisi", "Sanat", "arts_media", 8),
    ("Sosyal Medya Uzmanı", "Sanat", "sales_enterprise", 8),
    ("Ses Mühendisi", "Sanat", "arts_media", 7),
    ("Müzisyen (profesyonel)", "Sanat", "arts_media", 6),
    ("Oyuncu", "Sanat", "arts_media", 6),
    ("Reklam Metin Yazarı", "Sanat", "arts_media", 7),
    # Turizm & hizmet (14)
    ("Otel Müdürü", "Turizm", "service_hospitality", 7),
    ("Turizm Rehberi", "Turizm", "service_hospitality", 7),
    ("Uçuş Görevlisi", "Turizm", "service_hospitality", 7),
    ("Pilot", "Turizm", "engineering", 8),
    ("Gastronomi Şefi", "Turizm", "service_hospitality", 7),
    ("Pastacı", "Turizm", "service_hospitality", 6),
    ("Etkinlik Yöneticisi", "Turizm", "sales_enterprise", 8),
    ("Müşteri Deneyimi Uzmanı", "Turizm", "hr_people", 8),
    ("Çağrı Merkezi Uzmanı", "Turizm", "service_hospitality", 6),
    ("Barista", "Turizm", "service_hospitality", 5),
    ("Spor Antrenörü", "Turizm", "education", 7),
    ("Kişisel Antrenör", "Turizm", "health_support", 7),
    ("Güzellik Uzmanı", "Turizm", "service_hospitality", 6),
    ("Kuaför", "Turizm", "service_hospitality", 5),
    # Üretim & lojistik (16)
    ("Üretim Şefi", "Üretim", "logistics_production", 7),
    ("CNC Operatörü", "Üretim", "logistics_production", 6),
    ("Kaynakçı", "Üretim", "logistics_production", 6),
    ("Elektrik Teknisyeni", "Üretim", "engineering", 7),
    ("Bakım Teknisyeni", "Üretim", "logistics_production", 7),
    ("Lojistik Planlamacı", "Üretim", "logistics_production", 8),
    ("Depo Yöneticisi", "Üretim", "logistics_production", 7),
    ("Kurye Operasyon Yöneticisi", "Üretim", "logistics_production", 7),
    ("Kalite Kontrol Uzmanı", "Üretim", "logistics_production", 8),
    ("İş Güvenliği Uzmanı", "Üretim", "security_defense", 8),
    ("Çevre ve Atık Uzmanı", "Üretim", "agri_env", 8),
    ("Enerji Verimliliği Uzmanı", "Üretim", "engineering", 8),
    ("Otomasyon Teknisyeni", "Üretim", "engineering", 8),
    ("Robotik Teknisyeni", "Üretim", "engineering", 9),
    ("Tekstil Operatörü", "Üretim", "logistics_production", 5),
    ("Gıda Üretim Sorumlusu", "Üretim", "logistics_production", 7),
    # Tarım & çevre (10)
    ("Ziraat Mühendisi", "Tarım", "agri_env", 7),
    ("Orman Mühendisi", "Tarım", "agri_env", 7),
    ("Su Ürünleri Mühendisi", "Tarım", "agri_env", 7),
    ("Peyzaj Mimarı", "Tarım", "arts_media", 8),
    ("Sürdürülebilirlik Uzmanı", "Tarım", "agri_env", 9),
    ("İklim Uzmanı", "Tarım", "science_research", 8),
    ("Toprak Bilimci", "Tarım", "science_research", 7),
    ("Botanik Araştırmacısı", "Tarım", "science_research", 7),
    ("Hayvancılık Uzmanı", "Tarım", "agri_env", 7),
    ("Gıda Güvenliği Denetçisi", "Tarım", "health_clinical", 8),
    # İnşaat & teknik (12)
    ("Şantiye Şefi", "İnşaat", "engineering", 7),
    ("Mimarlık Teknikeri", "İnşaat", "engineering", 7),
    ("Quantity Surveyor", "İnşaat", "finance_ops", 8),
    ("Emlak Değerleme Uzmanı", "İnşaat", "finance_ops", 7),
    ("Gayrimenkul Danışmanı", "İnşaat", "sales_enterprise", 7),
    ("Şehir ve Bölge Planlamacı", "İnşaat", "engineering", 8),
    ("Ulaşım Planlamacı", "İnşaat", "engineering", 8),
    ("Jeoteknik Teknikeri", "İnşaat", "engineering", 7),
    ("İş Makinesi Operatörü", "İnşaat", "logistics_production", 5),
    ("Elektrik Proje Mühendisi", "İnşaat", "engineering", 8),
    ("Mekanik Tesisat Mühendisi", "İnşaat", "engineering", 8),
    ("Yangın Güvenliği Mühendisi", "İnşaat", "security_defense", 8),
    # İK & satış (8) — tamamlama
    ("Performans Yönetimi Uzmanı", "İK", "hr_people", 8),
    ("Ödül ve Yan Haklar Uzmanı", "İK", "finance_ops", 7),
    ("Kurumsal İletişim Uzmanı", "İK", "arts_media", 8),
    ("Satış Temsilcisi", "Satış", "sales_enterprise", 7),
    ("Hesap Yöneticisi (B2B)", "Satış", "sales_enterprise", 8),
    ("İş Geliştirme Uzmanı", "Satış", "sales_enterprise", 9),
    ("Pazarlama Müdürü", "Satış", "sales_enterprise", 8),
    ("Dijital Pazarlama Uzmanı", "Satış", "tech_creative", 9),
]

# (name, faculty, "t1|t2|t3", template)
_DEPT_RAW = [
    ("Tıp", "Tıp Fakültesi", "Genel|Tipte Uzmanlık|Araştırma", "health_clinical"),
    ("Diş Hekimliği", "Diş Hekimliği Fakültesi", "Genel|Cerrahi|Protetik", "health_clinical"),
    ("Eczacılık", "Eczacılık Fakültesi", "Endüstri|Klinik|Kozmetik", "health_clinical"),
    ("Veteriner Fakültesi", "Veteriner Fakültesi", "Klinik|Gıda|Halk sağlığı", "health_clinical"),
    ("Hemşirelik", "Sağlık Bilimleri Fakültesi", "Hemşirelik|Ebelik|Yoğun bakım", "health_support"),
    ("Fizyoterapi ve Rehabilitasyon", "Sağlık Bilimleri Fakültesi", "Spor|Nörolojik|Ortopedi", "health_support"),
    ("Beslenme ve Diyetetik", "Sağlık Bilimleri Fakültesi", "Klinik|Toplum|Spor", "health_support"),
    ("Odyoloji", "Sağlık Bilimleri Fakültesi", "İşitme|Denge|Koklear", "health_support"),
    ("Dil ve Konuşma Terapisi", "Sağlık Bilimleri Fakültesi", "Pediatrik|Nörolojik|Ses", "health_support"),
    ("Ergoterapi", "Sağlık Bilimleri Fakültesi", "Pediatrik|Geriatri|Psikososyal", "health_support"),
    ("Sosyal Hizmet", "İnsani Bilimler Fakültesi", "Aile|Kurumsal|Toplum", "health_support"),
    ("Psikoloji", "Fen-Edebiyat / İİBF", "Klinik|Endüstriyel|Gelişim", "health_support"),
    ("Bilgisayar Mühendisliği", "Mühendislik Fakültesi", "Yazılım|Donanım|Yapay zeka", "engineering"),
    ("Elektrik-Elektronik Mühendisliği", "Mühendislik Fakültesi", "Güç|İletişim|Kontrol", "engineering"),
    ("Elektronik ve Haberleşme Mühendisliği", "Mühendislik Fakültesi", "RF|Telekom|Gömülü", "engineering"),
    ("Endüstri Mühendisliği", "Mühendislik Fakültesi", "Üretim|Verimlilik|Yöneylem", "engineering"),
    ("Makine Mühendisliği", "Mühendislik Fakültesi", "Termodinamik|Üretim|Tasarım", "engineering"),
    ("İnşaat Mühendisliği", "Mühendislik Fakültesi", "Yapı|Ulaşım|Jeoteknik", "engineering"),
    ("Kimya Mühendisliği", "Mühendislik Fakültesi", "Proses|Enerji|Malzeme", "engineering"),
    ("Metalurji ve Malzeme Mühendisliği", "Mühendislik Fakültesi", "Malzeme|Korozyon|Nanomalzeme", "engineering"),
    ("Gıda Mühendisliği", "Mühendislik / Ziraat", "İşleme|Güvenlik|AR-GE", "engineering"),
    ("Tekstil Mühendisliği", "Mühendislik Fakültesi", "Üretim|Konfeksiyon|Teknik", "engineering"),
    ("Çevre Mühendisliği", "Mühendislik Fakültesi", "Su|Atık|Hava", "agri_env"),
    ("Jeoloji Mühendisliği", "Mühendislik Fakültesi", "Maden|Jeoteknik|Hidrojeoloji", "science_research"),
    ("Petrol ve Doğalgaz Mühendisliği", "Mühendislik Fakültesi", "Sondaj|Üretim|Depolama", "engineering"),
    ("Harita Mühendisliği (Geomatik)", "Mühendislik Fakültesi", "Ölçme|GIS|Fotogrametri", "engineering"),
    ("Uçak Mühendisliği", "Mühendislik Fakültesi", "Tasarım|Aerodinamik|Bakım", "engineering"),
    ("Uzay Mühendisliği", "Mühendislik Fakültesi", "Uydu|Roket|Sistem", "engineering"),
    ("Otomotiv Mühendisliği", "Mühendislik Fakültesi", "Tasarım|Üretim|Elektrikli araç", "engineering"),
    ("Biyomedikal Mühendisliği", "Mühendislik Fakültesi", "Cihaz|Görüntüleme|Yapay organ", "health_clinical"),
    ("Enerji Sistemleri Mühendisliği", "Mühendislik Fakültesi", "Yenilenebilir|Şebeke|Depolama", "engineering"),
    ("Yazılım Mühendisliği", "Mühendislik / Bilgisayar", "Backend|Güvenlik|Mobil", "tech_analytical"),
    ("Mimarlık", "Mimarlık Fakültesi", "Tasarım|Kentsel|Restorasyon", "arts_media"),
    ("İç Mimarlık ve Çevre Tasarımı", "Güzel Sanatlar / Mimarlık", "Konut|Ticari|Müze", "arts_media"),
    ("Şehir ve Bölge Planlama", "Mimarlık Fakültesi", "Ulaşım|Çevre|Kentsel dönüşüm", "engineering"),
    ("Endüstriyel Tasarım", "Güzel Sanatlar Fakültesi", "Ürün|Mobilya|Deneyim", "arts_media"),
    ("Grafik Tasarım", "Güzel Sanatlar Fakültesi", "Dijital|Marka|Tipografi", "arts_media"),
    ("Geleneksel Türk Sanatları", "Güzel Sanatlar Fakültesi", "Hat|Tezhip|Çini", "arts_media"),
    ("Müzik", "Devlet Konservatuvarı / GSF", "Performans|Kompozisyon|Eğitim", "arts_media"),
    ("Sahne Sanatları", "Devlet Konservatuvarı", "Drama|Opera|Dans", "arts_media"),
    ("Radyo, Televizyon ve Sinema", "İletişim Fakültesi", "Yönetmenlik|Kurgu|Prodüksiyon", "arts_media"),
    ("Halkla İlişkiler ve Tanıtım", "İletişim Fakültesi", "Kurumsal|Etkinlik|Dijital", "sales_enterprise"),
    ("Reklamcılık", "İletişim Fakültesi", "Kreatif|Medyaplannig|Marka", "arts_media"),
    ("Yeni Medya ve İletişim", "İletişim Fakültesi", "Veri görselleştirme|Sosyal medya", "tech_creative"),
    ("Gastronomi ve Mutfak Sanatları", "Uygulama Bilimler / Turizm", "Mutfak|Pastacılık|Yönetim", "service_hospitality"),
    ("Turizm İşletmeciliği", "Turizm Fakültesi", "Otel|Etkinlik|Destinasyon", "service_hospitality"),
    ("Turizm Rehberliği", "Turizm Fakültesi", "Kültürel|Doğa|Kongre", "service_hospitality"),
    ("Hukuk", "Hukuk Fakültesi", "Kamu|Özel|Uluslararası", "legal_public"),
    ("Uluslararası İlişkiler", "İİBF / Siyasal", "Diplomasi|Güvenlik|Ekonomi", "legal_public"),
    ("Siyaset Bilimi ve Kamu Yönetimi", "İİBF", "Kamu politikası|Yerel yönetim", "legal_public"),
    ("İktisat", "İİBF", "Teori|Politika|Ekonometri", "finance_ops"),
    ("İşletme", "İİBF", "Finans|Pazarlama|Yönetim", "sales_enterprise"),
    ("Maliye", "İİBF", "Vergi|Bütçe|Kamu maliyesi", "finance_ops"),
    ("Çalışma Ekonomisi ve Endüstri İlişkileri", "İİBF", "İK|Sendika|Ücret", "hr_people"),
    ("Yönetim Bilişim Sistemleri", "İİBF / Mühendislik", "ERP|Veri|Dijital dönüşüm", "tech_analytical"),
    ("Uluslararası Ticaret ve Finansman", "İİBF", "Dış ticaret|Risk|Finans", "finance_ops"),
    ("Matematik", "Fen Fakültesi", "Saf|Uygulamalı|İstatistik temeli", "science_research"),
    ("İstatistik", "Fen Fakültesi", "Veri bilimi|Biyoistatistik|Finans", "science_research"),
    ("Fizik", "Fen Fakültesi", "Teori|Malzeme|Astrofizik", "science_research"),
    ("Kimya", "Fen Fakültesi", "Analitik|Organik|Malzeme", "science_research"),
    ("Biyoloji", "Fen Fakültesi", "Moleküler|Ekoloji|Genetik", "science_research"),
    ("Moleküler Biyoloji ve Genetik", "Fen Fakültesi", "AR-GE|Sağlık|Biyoteknoloji", "science_research"),
    ("Arkeoloji", "Fen-Edebiyat Fakültesi", "Kazı|Müze|Kültürel miras", "science_research"),
    ("Sanat Tarihi", "Fen-Edebiyat Fakültesi", "Müze|Koruma|Eğitim", "arts_media"),
    ("Tarih", "Fen-Edebiyat Fakültesi", "Osmanlı|Çağdaş|Metodoloji", "education"),
    ("Sosyoloji", "Fen-Edebiyat Fakültesi", "Kent|Kültür|Kurumsal", "education"),
    ("Felsefe", "Fen-Edebiyat Fakültesi", "Etik|Mantık|Bilgi felsefesi", "education"),
    ("Antropoloji", "Fen-Edebiyat Fakültesi", "Kültür|Etnoğrafya|Tıbbi", "science_research"),
    ("Coğrafya", "Fen-Edebiyat Fakültesi", "Fiziki|Beşeri|GIS", "science_research"),
    ("Türk Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Eski Türk|Edebiyat|Dil bilimi", "education"),
    ("İngiliz Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Çeviri|Eğitim|Edebiyat", "education"),
    ("Çeviribilim", "Fen-Edebiyat Fakültesi", "Yazılı|Sözlü|Yerelleştirme", "arts_media"),
    ("İlahiyat", "İlahiyat Fakültesi", "Din bilimleri|Din eğitimi", "education"),
    ("İlköğretim Matematik Öğretmenliği", "Eğitim Fakültesi", "Ortaokul|Lise hazırlık", "education"),
    ("Fen Bilgisi Öğretmenliği", "Eğitim Fakültesi", "Ortaokul|Laboratuvar", "education"),
    ("Sınıf Öğretmenliği", "Eğitim Fakültesi", "İlkokul|Çoklu alan", "education"),
    ("Okul Öncesi Öğretmenliği", "Eğitim Fakültesi", "Kreş|Anaokulu", "education"),
    ("Rehberlik ve Psikolojik Danışmanlık", "Eğitim Fakültesi", "Okul|Kurumsal", "health_support"),
    ("Özel Eğitim Öğretmenliği", "Eğitim Fakültesi", "Zihin|Ortopedik|Dil", "education"),
    ("Beden Eğitimi ve Spor Öğretmenliği", "Spor Bilimleri Fakültesi", "Okul|Spor kulübü", "education"),
    ("Spor Yöneticiliği", "Spor Bilimleri Fakültesi", "Kulüp|Etkinlik|Pazarlama", "sales_enterprise"),
    ("Antrenörlük Eğitimi", "Spor Bilimleri Fakültesi", "Takım|Bireysel|Performans", "education"),
    ("Ziraat Mühendisliği", "Ziraat Fakültesi", "Bitki|Toprak|Sulama", "agri_env"),
    ("Orman Mühendisliği", "Orman Fakültesi", "Silvikültür|Koruma|ORMAN yangını", "agri_env"),
    ("Su Ürünleri Mühendisliği", "Su Ürünleri Fakültesi", "Üretim|İşleme|Koruma", "agri_env"),
    ("Peyzaj Mimarlığı", "Ziraat / Mimarlık", "Kentsel yeşil|Park|Ekoloji", "arts_media"),
    ("Bilgisayar ve Öğretim Teknolojileri Öğretmenliği", "Eğitim Fakültesi", "STEM|Dijital içerik", "education"),
    ("Mühendislik Bilimleri (doktora hazırlık)", "Fen Bilimleri Enstitüsü", "Disiplinler arası", "science_research"),
    ("Yapay Zeka ve Veri Mühendisliği", "Mühendislik Fakültesi", "ML|Büyük veri|Etik", "tech_analytical"),
    ("Robotik ve Otomasyon Mühendisliği", "Mühendislik Fakültesi", "Endüstri 4.0|Kontrol", "engineering"),
    ("Siber Güvenlik Mühendisliği", "Mühendislik Fakültesi", "Ağ|Uygulama|DFIR", "tech_analytical"),
    ("Oyun Tasarımı ve Programlama", "Güzel Sanatlar / Mühendislik", "Oyun mekaniği|Sanat", "tech_creative"),
    ("Moleküler Biyoteknoloji", "Mühendislik / Fen", "AR-GE|İlaç|Tarım biyotek", "science_research"),
    ("Actuarial Science / Aktüerya Bilimleri", "İİBF / Fen", "Sigorta|Risk|Finans", "finance_ops"),
    ("Uluslararası Ticaret", "İİBF", "Lojistik|Gümrük|Pazar", "sales_enterprise"),
    ("Lojistik Yönetimi", "İİBF", "Tedarik zinciri|Depo", "logistics_production"),
    ("Bankacılık ve Finans", "İİBF", "Kredi|Yatırım|Risk", "finance_ops"),
    ("Muhasebe ve Finansman", "İİBF", "Mali raporlama|Denetim", "finance_ops"),
    ("Kamu Yönetimi", "İİBF", "Strateji|Performans|Etik", "legal_public"),
    ("Çocuk Gelişimi", "Eğitim Fakültesi", "Erken çocukluk|Aile", "education"),
    ("Sınıf Öğretmenliği (İngilizce)", "Eğitim Fakültesi", "Çift dilli", "education"),
    ("Alman Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Çeviri|Eğitim", "education"),
    ("Fransız Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Çeviri|Eğitim", "education"),
    ("Müzik Öğretmenliği", "Eğitim / GSF", "Okul korosu|Enstrüman", "education"),
    ("Resim Öğretmenliği", "Eğitim / GSF", "Görsel sanatlar eğitimi", "education"),
    ("İşletme Mühendisliği", "Mühendislik Fakültesi", "Üretim sistemleri|Lean", "engineering"),
    ("Deniz Ulaştırma İşletme Mühendisliği", "Denizcilik Fakültesi", "Liman|Gemi işletme", "engineering"),
    ("Gemi Makineleri İşletme Mühendisliği", "Denizcilik Fakültesi", "Makine|Bakım", "engineering"),
    ("Gemi İnşaatı ve Gemi Makineleri Mühendisliği", "Denizcilik Fakültesi", "Tasarım|İnşa", "engineering"),
    ("Madencilik Mühendisliği", "Mühendislik Fakültesi", "Cevher|Yeraltı|Güvenlik", "engineering"),
    ("Tıbbi Mühendislik", "Mühendislik Fakültesi", "Görüntüleme|Biyosensör", "health_clinical"),
    ("Optik ve Akustik Mühendisliği", "Mühendislik Fakültesi", "Ses|Görüntü", "engineering"),
    ("Mekatronik Mühendisliği", "Mühendislik Fakültesi", "Robot|Kontrol|Elektronik", "engineering"),
    ("Bilgisayar Bilimleri", "Fen Fakültesi", "Teori|Algoritma|Kriptografi", "tech_analytical"),
    ("Veri Bilimi ve Analitiği", "Fen / Mühendislik", "İstatistik|ML|İş zekâsı", "tech_analytical"),
    ("Yapay Zeka Mühendisliği", "Mühendislik Fakültesi", "Derin öğrenme|Sistem", "tech_analytical"),
    ("Bilgi Güvenliği Mühendisliği", "Mühendislik Fakültesi", "Kriptografi|Ağ güvenliği", "tech_analytical"),
    ("Bilişim Sistemleri Mühendisliği", "Mühendislik Fakültesi", "Kurumsal sistem|Entegrasyon", "tech_analytical"),
    ("Jeofizik Mühendisliği", "Mühendislik Fakültesi", "Sismik|Yeraltı görüntüleme", "science_research"),
    ("Meteoroloji Mühendisliği", "Mühendislik / Fen", "Hava tahmini|İklim", "science_research"),
    ("Sivil Havacılık ve Uzay Bilimleri", "Mühendislik Fakültesi", "Hava trafiği|Uzay politikası", "engineering"),
    ("Raylı Sistemler Mühendisliği", "Mühendislik Fakültesi", "Metro|Demiryolu", "engineering"),
    ("Nanoteknoloji Mühendisliği", "Mühendislik Fakültesi", "Malzeme|AR-GE", "science_research"),
    ("Biyosistem Mühendisliği", "Mühendislik Fakültesi", "Tarım teknolojisi|Biyoprocess", "agri_env"),
    ("Astronomi ve Uzay Bilimleri", "Fen Fakültesi", "Gözlem|Kozmoloji", "science_research"),
    ("İspanyol Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Çeviri|Kültür", "education"),
    ("Rus Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Çeviri|Kültür", "education"),
    ("Çince Mütercim ve Tercümanlık", "Fen-Edebiyat Fakültesi", "İş Çincesi|Kültür", "education"),
    ("Arap Dili ve Belâgatı", "İlahiyat / Fen-Edebiyat", "Dinî metinler|Çeviri", "education"),
    ("Müzikoloji", "Devlet Konservatuvarı", "Etnomüzikoloji|Tarih", "arts_media"),
    ("Sahne Dekorları ve Kostümü", "Devlet Konservatuvarı", "Tiyatro|Opera", "arts_media"),
    ("Sinema ve Televizyon", "İletişim Fakültesi", "Yönetmenlik|Senaryo", "arts_media"),
    ("Gastronomi ve Culinary Arts", "Turizm Fakültesi", "Fine dining|Yönetim", "service_hospitality"),
    ("Rekreasyon Yönetimi", "Spor Bilimleri Fakültesi", "Etkinlik|Doğa sporları", "sales_enterprise"),
    ("Besyo Antrenörlük", "Spor Bilimleri Fakültesi", "Branş seçmeli", "education"),
    ("Besyo Rekreasyon", "Spor Bilimleri Fakültesi", "Açık hava|Sağlıklı yaşam", "service_hospitality"),
    ("Beslenme Bilimleri (lisans)", "Sağlık Bilimleri Fakültesi", "Toplum beslenmesi|AR-GE", "health_support"),
    ("Dil ve Konuşma Bozuklukları (logopedi)", "Sağlık Bilimleri Fakültesi", "Pediatrik|Nörolojik", "health_support"),
    ("Tıbbi Görüntüleme Teknikleri", "Sağlık Bilimleri Yüksekokulu", "Radyoloji destek", "health_clinical"),
    ("Anestezi (Önlisans)", "Sağlık Hizmetleri MYO", "Ameliyathane", "health_clinical"),
    ("Tıbbi Dokümantasyon ve Sekreterlik", "MYO", "Hastane bilgi sistemi", "finance_ops"),
    ("Ortopedik Protez ve Ortez", "Sağlık Bilimleri Fakültesi", "Rehabilitasyon teknolojisi", "health_support"),
    ("Ağız ve Diş Sağlığı (Önlisans)", "MYO", "Diş hekimi yardımcılığı", "health_clinical"),
    ("Tarımsal Yapılar ve Sulama", "Ziraat Fakültesi", "Sera|Baraj", "agri_env"),
    ("Bahçe Bitkileri", "Ziraat Fakültesi", "Sebze|Meyve|Bağ", "agri_env"),
    ("Tarla Bitkileri", "Ziraat Fakültesi", "Tahıl|Endüstri bitkisi", "agri_env"),
    ("Tarımsal Biyoteknoloji", "Ziraat Fakültesi", "Genetik|Islah", "science_research"),
    ("Ev Ekonomisi ve Beslenme (Eski)", "Eğitim / Aile", "Tüketici eğitimi", "education"),
    ("Aile ve Tüketici Bilimleri", "Eğitim Fakültesi", "Tüketici|Aile ekonomisi", "education"),
    ("Sınıf Öğretmenliği (İlköğretim Matematik)", "Eğitim Fakültesi", "STEM odaklı", "education"),
    ("Bilgisayar ve Öğretim Teknolojileri", "Eğitim Fakültesi", "Dijital okuryazarlık", "education"),
    ("Almanca Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Fransızca Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Tarih Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Coğrafya Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Felsefe Grubu Öğretmenliği", "Eğitim Fakültesi", "Din kültürü|Ahlak", "education"),
    ("Din Kültürü ve Ahlak Bilgisi Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("İmam-Hatip Lisesi Meslek Dersleri Öğretmenliği", "Eğitim Fakültesi", "Meslek dersleri", "education"),
    ("İlahiyat Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim din kültürü", "education"),
    ("Makine Resim ve Konstrüksiyon Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "engineering"),
    ("Elektrik-Elektronik Teknolojisi Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "engineering"),
    ("Bilişim Teknolojileri Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "tech_analytical"),
    ("Talaşlı Üretim Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "logistics_production"),
    ("İnşaat Teknolojisi Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "engineering"),
    ("Motorlu Araçlar Teknolojisi Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "engineering"),
    ("Gıda Teknolojisi Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "engineering"),
    ("Tekstil Teknolojisi Öğretmenliği", "Teknik Eğitim Fakültesi", "Meslek lisesi", "logistics_production"),
    ("Grafik Tasarımı Öğretmenliği", "Güzel Sanatlar Eğitimi", "Meslek lisesi", "arts_media"),
    ("Resim Öğretmenliği (GSF)", "Güzel Sanatlar Eğitimi", "Ortaöğretim görsel", "education"),
    ("Müzik Öğretmenliği (GSF)", "Güzel Sanatlar Eğitimi", "Ortaöğretim müzik", "education"),
    ("Sinema ve Dijital Medya", "İletişim Fakültesi", "Prodüksiyon|Post", "arts_media"),
    ("Halkla İlişkiler ve Reklamcılık", "İletişim Fakültesi", "Entegre iletişim", "sales_enterprise"),
    ("Kültür ve İletişim Bilimleri", "İletişim Fakültesi", "Kültürel çalışmalar", "education"),
    ("Fotoğraf", "İletişim / GSF", "Belgesel|Sanat", "arts_media"),
    ("Kütüphanecilik", "İletişim / Eğitim", "Dijital arşiv|Bilgi okuryazarlığı", "finance_ops"),
    ("Arşivcilik", "İletişim / İİBF", "Belge yönetimi", "finance_ops"),
    ("Coğrafi Bilgi Sistemleri", "Mühendislik / Coğrafya", "Uzaktan algılama|Harita", "engineering"),
    ("Kentsel Tasarım ve Peyzaj Mimarlığı", "Mimarlık Fakültesi", "Açık alan|Yeşil altyapı", "arts_media"),
    ("Mimarlık (Restorasyon)", "Mimarlık Fakültesi", "Tarihi yapı|Koruma", "arts_media"),
    ("İslami İlimler", "İlahiyat Fakültesi", "Fıkıh|Tefsir|Hadis", "education"),
    ("Felsefe ve Din Bilimleri", "İlahiyat Fakültesi", "Din felsefesi", "education"),
    ("Uluslararası Öğrenci İşleri ve Diplomasi", "İİBF", "Eğitim diplomasisi|Kültür", "legal_public"),
    ("Avrupa Birliği Çalışmaları", "İİBF", "Politika|Hukuk", "legal_public"),
    ("Çalışma Sosyolojisi ve Endüstri İlişkileri", "İİBF", "İş hukuku|Sosyoloji", "hr_people"),
    ("İşletme (İngilizce)", "İİBF", "Uluslararası işletme", "sales_enterprise"),
    ("İktisat (İngilizce)", "İİBF", "Uluslararası ekonomi", "finance_ops"),
    ("Siyaset Bilimi", "İİBF / Siyasal Bilgiler", "Kamu politikası|Partiler", "legal_public"),
    ("Kamu Yönetimi (MYO)", "MYO", "Büro yönetimi|Kamu", "finance_ops"),
    ("Yerel Yönetimler", "MYO", "Belediye|İl özel idare", "legal_public"),
    ("Sivil Hava Ulaştırma İşletmeciliği", "Uygulama Bilimler Yüksekokulu", "Havalimanı operasyon", "service_hospitality"),
    ("Pilotaj (Önlisans)", "Havacılık Yüksekokulu", "Uçuş eğitimi", "engineering"),
    ("Uçuş Harekatı", "Havacılık Yüksekokulu", "Dispatch|Planlama", "logistics_production"),
    ("Denizcilik İşletmeleri Yönetimi", "Denizcilik Fakültesi", "Liman lojistik", "sales_enterprise"),
    ("Deniz Ulaştırma İşletme Mühendisliği (Gemi)", "Denizcilik Fakültesi", "İşletme|Liman", "engineering"),
    ("Balıkçılık Teknolojisi Mühendisliği", "Su Ürünleri Fakültesi", "Üretim|İşleme", "agri_env"),
    ("Su Bilimleri ve Mühendisliği", "Mühendislik Fakültesi", "Hidrolik|Atık su", "agri_env"),
    ("Ortez ve Protez (MYO)", "Sağlık Hizmetleri MYO", "Teknik destek", "health_support"),
    ("Tıbbi Laboratuvar Teknikleri", "Sağlık Hizmetleri MYO", "Analiz|Kalite", "science_research"),
    ("Eczane Hizmetleri", "Sağlık Hizmetleri MYO", "Reçete|Stok", "health_clinical"),
    ("Çocuk Gelişimi (MYO)", "Sosyal Bilimler MYO", "Kreş destek", "education"),
    ("Yaşlı Bakımı", "Sağlık Hizmetleri MYO", "Huzurevi|Ev bakım", "health_support"),
    ("İlk ve Acil Yardım (Önlisans)", "Sağlık Hizmetleri MYO", "Ambulans|Acil", "health_support"),
    ("Tıbbi Tanıtım ve Pazarlama", "Sağlık Bilimleri", "İlaç tanıtımı", "sales_enterprise"),
    ("Sağlık Yönetimi", "Sağlık Bilimleri Fakültesi", "Hastane yönetimi|Kalite", "finance_ops"),
    ("Ağız ve Diş Sağlığı (lisans)", "Diş Hekimliği Fakültesi", "Koruyucu diş hekimliği", "health_clinical"),
    ("Endodonti (Uzmanlık öncesi lisans)", "Diş Hekimliği", "Kök kanalı", "health_clinical"),
    ("Patoloji Laboratuvar Teknikleri", "Sağlık MYO", "Histoloji", "science_research"),
    ("Biyoteknoloji", "Fen Fakültesi", "Endüstriyel biyotek|AR-GE", "science_research"),
    ("Genetik", "Fen Fakültesi", "İnsan|Bitki genetiği", "science_research"),
    ("Madencilik ve Yerbilimleri", "Mühendislik Fakültesi", "Cevher hazırlama", "engineering"),
    ("Fizik Mühendisliği", "Mühendislik Fakültesi", "Malzeme|Nükleer uygulama", "science_research"),
    ("Kimya Mühendisliği (Biyomoleküler)", "Mühendislik Fakültesi", "İlaç prosesi", "science_research"),
    ("Enerji Mühendisliği", "Mühendislik Fakültesi", "Isı|Güç sistemleri", "engineering"),
    ("Makine Mühendisliği (Otomotiv)", "Mühendislik Fakültesi", "Araç tasarımı", "engineering"),
    ("Makine Mühendisliği (Üretim)", "Mühendislik Fakültesi", "CNC|Kalıp", "logistics_production"),
    ("Endüstriyel Sistemler Mühendisliği", "Mühendislik Fakültesi", "Simülasyon|Ergonomi", "engineering"),
    ("İmalat Mühendisliği", "Mühendislik Fakültesi", "Katmanlı üretim|Prototip", "engineering"),
    ("Kontrol ve Otomasyon Mühendisliği", "Mühendislik Fakültesi", "SCADA|Sensör", "engineering"),
    ("Telekomünikasyon Mühendisliği", "Mühendislik Fakültesi", "5G|Fiber", "engineering"),
    ("Yazılım ve Veri Bilimi (Fen)", "Fen Fakültesi", "Disiplinler arası", "tech_analytical"),
    ("İslami Finans ve Ekonomi", "İİBF / İlahiyat", "Sukuk|Etik finans", "finance_ops"),
    ("Sermaye Piyasası", "İİBF", "Analist|Aracı kurum", "finance_ops"),
    ("Sigortacılık ve Risk Yönetimi", "İİBF", "Aktüerya|Hasar", "finance_ops"),
    ("Gayrimenkul Geliştirme ve Finansmanı", "İİBF", "Proje finansmanı", "finance_ops"),
    ("Kültür Varlıklarını Koruma ve Onarım", "Mimarlık / GSF", "Restorasyon uzmanlığı", "arts_media"),
    ("Müzeoloji", "Fen-Edebiyat / İletişim", "Koleksiyon|Eğitim", "education"),
    ("Kültür Yönetimi", "İletişim / İİBF", "Sanat kurumları|Festival", "sales_enterprise"),
    ("Moda Tasarımı", "Güzel Sanatlar Fakültesi", "Konfeksiyon|Tekstil tasarım", "arts_media"),
    ("Tekstil ve Moda Tasarımı", "Güzel Sanatlar Fakültesi", "Sürdürülebilir moda", "arts_media"),
    ("El Sanatları Tasarımı ve Üretimi", "Güzel Sanatlar Fakültesi", "Geleneksel|Çağdaş", "arts_media"),
    ("Seramik ve Cam Tasarımı", "Güzel Sanatlar Fakültesi", "Endüstriyel sanat", "arts_media"),
    ("Tipografi ve İletişim Tasarımı", "Güzel Sanatlar Fakültesi", "Harf|Dijital", "arts_media"),
    ("Dijital Oyun Tasarımı", "Güzel Sanatlar / Mühendislik", "Level tasarımı|Sanat", "tech_creative"),
    ("Animasyon", "Güzel Sanatlar Fakültesi", "2D|3D|Karakter", "arts_media"),
    ("Film Tasarımı ve Yönetmenliği", "İletişim Fakültesi", "Kurgu|Görüntü", "arts_media"),
    ("Tiyatro Eleştirmenliği ve Dramaturji", "Devlet Konservatuvarı", "Metin|Sahne", "arts_media"),
    ("Opera Şan", "Devlet Konservatuvarı", "Solo|Koro", "arts_media"),
    ("Bale", "Devlet Konservatuvarı", "Dans|Koreografi", "arts_media"),
    ("Müzik Teorisi", "Devlet Konservatuvarı", "Komposisyon|Analiz", "education"),
    ("Popüler Müzik", "Devlet Konservatuvarı / GSF", "Caz|Rock|Prodüksiyon", "arts_media"),
    ("Etnomüzikoloji", "Müzikoloji bölümü", "Dünya müzikleri", "science_research"),
    ("Din Kültürü ve Ahlak Bilgisi (İlahiyat)", "İlahiyat Fakültesi", "Öğretmenlik hazırlığı", "education"),
    ("Uluslararası Ticaret ve Lojistik", "İİBF", "Gümrük|Tedarik", "logistics_production"),
    ("E-Ticaret ve Dijital Pazarlama", "İİBF / Uygulama", "Pazaryeri|SEO", "tech_creative"),
    ("İş Analitiği ve Veri Bilimi", "İİBF", "İş zekâsı|SQL", "tech_analytical"),
    ("Sürdürülebilir Turizm", "Turizm Fakültesi", "Ekoturizm|Toplum", "agri_env"),
    ("Otel Yöneticiliği", "Turizm Fakültesi", "Operasyon|Gelir", "sales_enterprise"),
    ("Konaklama İşletmeciliği", "Turizm Fakültesi", "Misafir deneyimi", "service_hospitality"),
    ("Turizm Rehberliği (İngilizce)", "Turizm Fakültesi", "Yabancı dil ağırlıklı", "service_hospitality"),
    ("Bahçe Bitkileri (Önlisans)", "Ziraat MYO", "Sera teknikeri", "agri_env"),
    ("Tıbbi ve Aromatik Bitkiler", "Ziraat Fakültesi", "İlaç bitkisi|Uçucu yağ", "agri_env"),
    ("Süt Teknolojisi", "Ziraat Fakültesi", "Süt ürünleri|Kalite", "engineering"),
    ("Hayvan Bilimi ve Veterinerlik (Tarım)", "Ziraat Fakültesi", "Hayvan besleme", "agri_env"),
    ("Bitki Koruma", "Ziraat Fakültesi", "Entegre mücadele", "agri_env"),
    ("Toprak Bilimi ve Bitki Besleme", "Ziraat Fakültesi", "Gübre|Analiz", "science_research"),
    ("Tarımsal Ekonomi", "Ziraat Fakültesi", "Politika|Piyasa", "finance_ops"),
    ("Orman Endüstri Mühendisliği", "Orman Fakültesi", "Ağaç işleme|Mobilya", "engineering"),
    ("Ağaç İşleri Endüstri Mühendisliği", "Orman Fakültesi", "Tomruk|Kaplama", "engineering"),
    ("Yaban Hayatı Ekolojisi ve Yönetimi", "Orman Fakültesi", "Koruma alanları", "agri_env"),
    ("Peyzaj Mimarlığı (Ziraat)", "Ziraat Fakültesi", "Kırsal peyzaj", "arts_media"),
    ("Sütçülük Teknolojisi", "Ziraat Fakültesi", "Çiftlik|İşleme", "agri_env"),
    ("Arıcılık", "Ziraat Fakültesi", "Bal|Polinasyon", "agri_env"),
    ("Denizcilik İşletmeleri Yönetimi (MYO)", "Denizcilik MYO", "Liman büro", "logistics_production"),
    ("Gemi Makineleri İşletmeciliği (MYO)", "Denizcilik MYO", "Makine dairesi", "engineering"),
    ("Deniz Ulaştırma İşletmeciliği Mühendisliği", "Denizcilik Fakültesi", "Filo yönetimi", "engineering"),
    ("Savunma Sanayi Mühendisliği", "Mühendislik Fakültesi", "Sistem entegrasyon", "security_defense"),
    ("Uzaktan Algılama ve Coğrafi Bilgi Sistemleri", "Mühendislik / Coğrafya", "Uydu|Harita", "engineering"),
    ("Bilgisayar ve Öğretim Teknolojileri (Fen Bilimleri)", "Eğitim Fakültesi", "Fen laboratuvarı", "education"),
    ("Matematik Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Fizik Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Kimya Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Biyoloji Öğretmenliği", "Eğitim Fakültesi", "Ortaöğretim", "education"),
    ("Okul Öncesi Öğretmenliği (İngilizce)", "Eğitim Fakültesi", "Çift dilli anaokulu", "education"),
    ("Özel Eğitim (Zihin Yetersizliği)", "Eğitim Fakültesi", "Özel eğitim", "education"),
    ("Özel Eğitim (İşitme Engelliler)", "Eğitim Fakültesi", "İşitme", "education"),
    ("Özel Eğitim (Görme Engelliler)", "Eğitim Fakültesi", "Görme", "education"),
    ("Yabancı Dil Olarak Türkçe Öğretimi", "Eğitim Fakültesi", "YÖS|Yunus Emre", "education"),
    ("Yunanca Mütercim ve Tercümanlık", "Fen-Edebiyat Fakültesi", "Klasik diller", "education"),
    ("Latince Mütercim ve Tercümanlık", "Fen-Edebiyat Fakültesi", "Hukuk|Teoloji metinleri", "education"),
    ("İtalyan Dili ve Edebiyatı", "Fen-Edebiyat Fakültesi", "Dil ve kültür", "education"),
    ("Japonca Mütercim ve Tercümanlık", "Fen-Edebiyat Fakültesi", "İş Japoncası", "education"),
    ("Korece Mütercim ve Tercümanlık", "Fen-Edebiyat Fakültesi", "K-Pop kültürü|İş dili", "education"),
    ("Belarusça / Slav Dilleri", "Fen-Edebiyat Fakültesi", "Dilbilim", "education"),
    ("Karşılaştırmalı Edebiyat", "Fen-Edebiyat Fakültesi", "Dünya edebiyatı", "education"),
    ("Kültürel Miras ve Turizm", "Fen-Edebiyat Fakültesi", "Kültür rotaları", "service_hospitality"),
    ("Bilgi ve Belge Yönetimi", "İletişim Fakültesi", "Arşiv|Kütüphane bilimleri", "finance_ops"),
    ("Yayıncılık", "İletişim Fakültesi", "Kitap|Dergi|Dijital", "arts_media"),
    ("Basın ve Yayın", "İletişim Fakültesi", "Gazete|Haber ajansı", "arts_media"),
    ("Medya ve İletişim", "İletişim Fakültesi", "Genel iletişim", "arts_media"),
    ("Görsel İletişim Tasarımı", "İletişim Fakültesi", "Infografik|Marka", "arts_media"),
    ("İletişim Tasarımı ve Yönetimi", "İletişim Fakültesi", "Kurumsal iletişim", "sales_enterprise"),
    ("Politika ve Kamu Hizmetleri", "Siyasal Bilgiler", "Kamu politikası uygulama", "legal_public"),
    ("Kamu Politikası ve Yönetişim", "İİBF", "Politika analizi", "legal_public"),
    ("Kamu ve Siyaset Bilimi", "İİBF", "Karşılaştırmalı politika", "legal_public"),
    ("Uluslararası İlişkiler ve Avrupa Çalışmaları", "İİBF", "AB dış politikası", "legal_public"),
    ("Kamu Hukuku", "Hukuk Fakültesi", "İdare|Anayasa", "legal_public"),
    ("Özel Hukuk", "Hukuk Fakültesi", "Borçlar|Aile", "legal_public"),
    ("Ceza Hukuku ve Kriminoloji", "Hukuk Fakültesi", "Ceza muhakemesi", "legal_public"),
    ("Uluslararası Hukuk", "Hukuk Fakültesi", "Hukukun genel teorisi", "legal_public"),
    ("Hukuk ve İktisat", "Hukuk Fakültesi", "Disiplinler arası", "legal_public"),
    ("Adalet (Önlisans)", "MYO", "Adliyeler|Zabıt", "legal_public"),
    ("Güvenlik ve Koruma (Önlisans)", "MYO", "Özel güvenlik", "security_defense"),
    ("Polislik (POMEM öncesi lisans)", "Güvenlik Bilimleri", "Kriminoloji temeli", "security_defense"),
    ("Siber Güvenlik (lisans)", "Mühendislik Fakültesi", "BT güvenliği", "tech_analytical"),
    ("Felsefe (Mantık)", "Fen-Edebiyat Fakültesi", "Sembolik mantık", "science_research"),
    ("Din Felsefesi", "İlahiyat Fakültesi", "Modern düşünce", "education"),
    ("İslam Ekonomisi ve Finans", "İlahiyat / İİBF", "Zekat|Sukuk", "finance_ops"),
    ("Hadis", "İlahiyat Fakültesi", "Hadis ilimleri", "education"),
    ("Tefsir", "İlahiyat Fakültesi", "Kur'an ilimleri", "education"),
    ("Fıkıh", "İlahiyat Fakültesi", "İslam hukuku", "legal_public"),
    ("Kelam", "İlahiyat Fakültesi", "İslam düşüncesi", "education"),
    ("Din Kültürü ve Ahlak Bilgisi (İlahiyat lisans)", "İlahiyat Fakültesi", "Alan öğretmenliği", "education"),
    ("Din Psikolojisi ve Rehberlik", "İlahiyat Fakültesi", "Pastoral psikoloji", "health_support"),
    ("Dinler Tarihi", "İlahiyat Fakültesi", "Karşılaştırmalı din", "education"),
    ("Hristiyanlık ve Yahudilik", "İlahiyat Fakültesi", "Semavi dinler", "education"),
    ("İlahiyat (İngilizce)", "İlahiyat Fakültesi", "Uluslararası ilahiyat", "education"),
    ("Sosyal Hizmetler ve Danışmanlık", "İnsani Bilimler", "Kurumsal sosyal hizmet", "health_support"),
    ("Çalışma Ekonomisi ve Endüstri İlişkileri (İİBF)", "İİBF", "Sendika|Toplu iş", "hr_people"),
    ("İş Sağlığı ve Güvenliği (lisans)", "Mühendislik / Sağlık", "OSGB|Risk", "security_defense"),
    ("İşletme Yönetimi (MYO)", "MYO", "Ofis yönetimi", "finance_ops"),
    ("Muhasebe ve Vergi Uygulamaları (MYO)", "MYO", "Mali müşavirlik destek", "finance_ops"),
    ("Bankacılık ve Sigortacılık (MYO)", "MYO", "Şube operasyonları", "finance_ops"),
    ("Dış Ticaret (MYO)", "MYO", "Gümrük|İthalat", "sales_enterprise"),
    ("Lojistik (MYO)", "MYO", "Depo|Sevkiyat", "logistics_production"),
    ("Büro Yönetimi ve Yönetici Asistanlığı", "MYO", "İdari destek", "finance_ops"),
    ("Hukuk Büro Yönetimi ve Sekreterliği", "MYO", "Hukuk bürosu", "legal_public"),
    ("Anestezi (Lisans)", "Sağlık Bilimleri", "Anestezi teknikeri lisans", "health_clinical"),
    ("Fizyoterapi ve Rehabilitasyon (İngilizce)", "Sağlık Bilimleri", "Uluslararası hasta", "health_support"),
    ("Dil ve Konuşma Bozuklukları (İngilizce)", "Sağlık Bilimleri", "Çift dilli terapi", "health_support"),
    ("Beslenme ve Diyetetik (İngilizce)", "Sağlık Bilimleri", "Klinik diyet", "health_support"),
    ("Ebelik", "Sağlık Bilimleri Fakültesi", "Doğum|Anne sağlığı", "health_clinical"),
    ("Hemşirelik (İngilizce)", "Sağlık Bilimleri", "Uluslararası hemşirelik", "health_support"),
    ("Tıp (İngilizce)", "Tıp Fakültesi", "İngilizce tıp programı", "health_clinical"),
    ("Diş Hekimliği (İngilizce)", "Diş Hekimliği", "İngilizce diş", "health_clinical"),
    ("Veteriner Fakültesi (İngilizce)", "Veteriner Fakültesi", "Uluslararası veteriner", "health_clinical"),
    ("Moleküler Biyoloji ve Genetik (İngilizce)", "Fen Fakültesi", "AR-GE odaklı", "science_research"),
    ("Mühendislik Programları (İngilizce)", "Mühendislik Fakültesi", "International engineering", "engineering"),
    ("İktisadi ve İdari Bilimler Programları (İngilizce)", "İİBF", "International business", "sales_enterprise"),
]


def merge_template(tpl_name: str) -> dict:
    t = TEMPLATES[tpl_name]
    return json.loads(json.dumps(t))


def main():
    raw_prof = _PROF_RAW[:200]
    assert len(raw_prof) == 200
    OUT.mkdir(parents=True, exist_ok=True)
    profs = []
    for i, (title, cat, tpl, fut) in enumerate(raw_prof, 1):
        base = merge_template(tpl)
        profs.append(
            {
                "id": f"prof-{i:03d}",
                "title": title,
                "category": cat,
                "futureOutlook": fut,
                **base,
            }
        )
    depts = []
    for i, (name, fac, tracks, tpl) in enumerate(_DEPT_RAW, 1):
        base = merge_template(tpl)
        depts.append(
            {
                "id": f"dep-{i:03d}",
                "name": name,
                "faculty": fac,
                "tracks": [x.strip() for x in tracks.split("|") if x.strip()],
                **base,
            }
        )
    (OUT / "professions.json").write_text(
        json.dumps(profs, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (OUT / "departments.json").write_text(
        json.dumps(depts, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print("professions", len(profs), "departments", len(depts))


if __name__ == "__main__":
    main()
