export type HeroLiveSample = {
  mbti: string;
  match: number;
  title: string;
  blurb: string;
  tags: [string, string, string];
};

/** Canlı hero önizlemesi — sırayla dönen örnek eşleşmeler (örnek veri). */
export const HERO_LIVE_SAMPLES: HeroLiveSample[] = [
  {
    mbti: "INFJ",
    match: 92,
    title: "Ürün tasarımcısı",
    blurb: "Veri ve empati profilin bu yolu öne çıkarıyor.",
    tags: ["Empati", "Sistem", "Yaratıcı"],
  },
  {
    mbti: "ENTP",
    match: 88,
    title: "Ürün yöneticisi",
    blurb: "Fikir üretimi ve ikna gücün yenilikçi rollere uyuyor.",
    tags: ["Strateji", "İletişim", "Esneklik"],
  },
  {
    mbti: "ISTJ",
    match: 91,
    title: "Finansal analist",
    blurb: "Düzen ve detay odaklı çalışma stilin güçlü bir sinyal.",
    tags: ["Analitik", "Güvenilirlik", "Planlama"],
  },
  {
    mbti: "ENFP",
    match: 85,
    title: "İçerik stratejisti",
    blurb: "Hikâye anlatımı ve merakın içerik dünyasında parlar.",
    tags: ["Yaratıcılık", "Enerji", "İnsan"],
  },
  {
    mbti: "INTJ",
    match: 94,
    title: "Yazılım mimarı",
    blurb: "Uzun vadeli sistem düşüncen teknik liderlikle örtüşüyor.",
    tags: ["Mimari", "Odak", "Mantık"],
  },
  {
    mbti: "ISFJ",
    match: 89,
    title: "İnsan kaynakları uzmanı",
    blurb: "Destekleyici yaklaşımın insan odaklı rollerde öne çıkıyor.",
    tags: ["Dinleme", "Sadakat", "Düzen"],
  },
  {
    mbti: "ESTP",
    match: 82,
    title: "Satış mühendisi",
    blurb: "Hızlı karar ve sahada olmayı seven profilin eşleşiyor.",
    tags: ["Aksiyon", "Pragmatik", "İkna"],
  },
  {
    mbti: "INFP",
    match: 87,
    title: "UX araştırmacısı",
    blurb: "Kullanıcı ihtiyacını hissetmen araştırma rollerine uyuyor.",
    tags: ["Merhamet", "Derinlik", "Gözlem"],
  },
  {
    mbti: "ESTJ",
    match: 90,
    title: "Operasyon müdürü",
    blurb: "Sonuç odaklı organizasyon becerin operasyonlarda değerli.",
    tags: ["Liderlik", "Verimlilik", "Netlik"],
  },
  {
    mbti: "INTP",
    match: 93,
    title: "Veri bilimci",
    blurb: "Kavramsal modelleme ve merakın analitik rollerle uyumlu.",
    tags: ["Teori", "Sorgulama", "Özgünlük"],
  },
  {
    mbti: "ESFJ",
    match: 86,
    title: "Eğitim tasarımcısı",
    blurb: "Topluluk kurma isteğin öğrenme deneyimlerinde parlıyor.",
    tags: ["Harmoni", "Pratiklik", "Paylaşım"],
  },
  {
    mbti: "ISTP",
    match: 84,
    title: "Siber güvenlik uzmanı",
    blurb: "Ellerin kirlenmesinden çekinmeyen problem çözücü profilsin.",
    tags: ["Teknik", "Sakin", "Çözüm"],
  },
  {
    mbti: "ENFJ",
    match: 91,
    title: "Topluluk yöneticisi",
    blurb: "İlham verme ve koçluk doğan yeteneklerinden biri.",
    tags: ["Vizyon", "Empati", "Organize"],
  },
  {
    mbti: "ISFP",
    match: 83,
    title: "Görsel iletişim tasarımcısı",
    blurb: "Estetik hassasiyetin marka ve görsel hikâyede öne çıkıyor.",
    tags: ["Estetik", "Dürüstlük", "Deneyim"],
  },
  {
    mbti: "ENTJ",
    match: 95,
    title: "Büyüme stratejisti",
    blurb: "Hedef koyma ve yürütme gücün strateji rollerine çok uygun.",
    tags: ["Karar", "Ölçek", "Cesaret"],
  },
  {
    mbti: "ESFP",
    match: 80,
    title: "Etkinlik yöneticisi",
    blurb: "Sahne enerjin deneyim ve etkinlik dünyasında eşleşiyor.",
    tags: ["Canlılık", "Pratik", "İnsan"],
  },
  {
    mbti: "INTJ",
    match: 89,
    title: "Yatırım analisti",
    blurb: "Uzun vadeli düşünce ve disiplinin finansal analizde güçlü.",
    tags: ["Tahmin", "Disiplin", "Bağımsızlık"],
  },
  {
    mbti: "ENFP",
    match: 88,
    title: "Marka iletişimcisi",
    blurb: "Özgün ses ve bağ kurma isteğin marka rollerinde parlıyor.",
    tags: ["Özgünlük", "Heyecan", "Bağ"],
  },
  {
    mbti: "ISTJ",
    match: 92,
    title: "Kalite güvence mühendisi",
    blurb: "Standart ve süreç odaklı çalışman kalite süreçlerine uyuyor.",
    tags: ["Hassasiyet", "Süreç", "Güven"],
  },
  {
    mbti: "INFJ",
    match: 86,
    title: "Kullanıcı deneyimi yazarı",
    blurb: "İnsan dilinden konuşman mikro metinlerde fark yaratır.",
    tags: ["Ton", "Empati", "Netlik"],
  },
  {
    mbti: "ENTP",
    match: 87,
    title: "Startup kurucu ortağı",
    blurb: "Çok yönlü düşünce ve risk iştahın girişimcilikle örtüşüyor.",
    tags: ["İnovasyon", "Tartışma", "Hız"],
  },
  {
    mbti: "ISFJ",
    match: 90,
    title: "Hasta koordinatörü",
    blurb: "Bakım ve detay bir arada — sağlık hizmeti rollerine yakın.",
    tags: ["Şefkat", "Organizasyon", "Sabır"],
  },
  {
    mbti: "ESTP",
    match: 81,
    title: "Saha proje yöneticisi",
    blurb: "Anlık problem çözme ve sahada olma gücün öne çıkıyor.",
    tags: ["Müzakere", "Pratiklik", "Tempo"],
  },
  {
    mbti: "INFP",
    match: 84,
    title: "Psikoloji öğrencisi yolu",
    blurb: "Anlam arayışın insan bilimleri ve danışmanlık yollarına uyuyor.",
    tags: ["Derinlik", "Değer", "Dinleme"],
  },
  {
    mbti: "INTP",
    match: 91,
    title: "Araştırma geliştirici",
    blurb: "Yeni teknoloji keşfi ve deneme merakın Ar-Ge ile eşleşiyor.",
    tags: ["Merak", "Deneysel", "Odak"],
  },
  {
    mbti: "ISTJ",
    match: 90,
    title: "Çiftçi (bitkisel üretim)",
    blurb: "Düzen, doğa ve elle tutulur sonuç — Holland profilin sahayı öne çıkarıyor.",
    tags: ["Disiplin", "Doğa", "Uygulama"],
  },
  {
    mbti: "ISTP",
    match: 89,
    title: "Oto mekaniği teknisyeni",
    blurb: "Teşhis ve tamirde sakin, pratik zihnin teknik rollerle örtüşüyor.",
    tags: ["Mekanik", "Problem", "Eller"],
  },
  {
    mbti: "ESTP",
    match: 86,
    title: "Elektrik tesisatçısı",
    blurb: "Anında çözüm ve sahada olma tercihin montaj ve servis işlerine uyuyor.",
    tags: ["Saha", "Pratik", "Risk yönetimi"],
  },
  {
    mbti: "ISFP",
    match: 84,
    title: "Marangoz ve doğrama ustası",
    blurb: "Malzeme ve estetik hassasiyetin ahşap işçiliğinde değer katar.",
    tags: ["Estetik", "Ustalık", "Detay"],
  },
  {
    mbti: "ESFJ",
    match: 87,
    title: "Aşçı ve mutfak elemanı",
    blurb: "Misafirperverlik ve ritim duygun mutfak ekiplerinde öne çıkıyor.",
    tags: ["Hizmet", "Takım", "Düzen"],
  },
  {
    mbti: "ISFJ",
    match: 88,
    title: "Güzellik ve cilt bakım uzmanı",
    blurb: "Bakım ve güven ortamı kurma becerin yüz yüze hizmette parlıyor.",
    tags: ["Şefkat", "Hijyen", "Güven"],
  },
  {
    mbti: "ESTJ",
    match: 85,
    title: "Depo ve lojistik görevlisi",
    blurb: "Süreç ve sorumluluk odaklı çalışman stok ve sevkiyatta eşleşiyor.",
    tags: ["Organizasyon", "Netlik", "Verim"],
  },
  {
    mbti: "INTJ",
    match: 88,
    title: "CNC torna-freze operatörü",
    blurb: "Kesin ölçü ve sistem düşüncen hassas imalat rollerine yakın duruyor.",
    tags: ["Hassasiyet", "Sistem", "Odak"],
  },
];
